import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


class Config:
    """Application configuration, read from environment variables.

    No sensitive data is required: the app is meant for strictly local,
    unauthenticated use.
    """

    SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key-change-me")

    _db_path = os.environ.get("DATABASE_PATH", "instance/biblio.sqlite3")
    SQLALCHEMY_DATABASE_URI = "sqlite:///" + str(BASE_DIR / _db_path)
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    # Book covers
    COVERS_DIR = BASE_DIR / "app" / "static" / "covers"
    COVER_MAX_SIZE = (600, 900)  # max width / height in pixels

    # Self-signed HTTPS certificate (generated by entrypoint.sh), exposed for
    # download to allow installing it as a trusted profile on iOS (needed to
    # unlock camera access in Safari).
    CERT_DIR = BASE_DIR / "certs"

    # Contact info sent in the User-Agent header of calls to Open Library:
    # Open Library grants a 3x more generous rate limit to identified
    # requests (see isbn_service.py).
    CONTACT_INFO = os.environ.get("CONTACT_INFO", "")

    ITEMS_PER_PAGE = 60
